/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as BookRepairRouteImport } from './routes/book-repair'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MobilesRouteImport } from './routes/mobiles'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TradeInRouteImport } from './routes/trade-in'
import { Route as UsedRouteImport } from './routes/used'
import { Route as AccessoriesCategoryRouteImport } from './routes/accessories.$category'
import { Route as MobilesIndexRouteImport } from './routes/mobiles.index'
import { Route as MobilesBrandRouteImport } from './routes/mobiles.$brand'
import { Route as RepairServiceRouteImport } from './routes/repair.$service'
import { Route as UsedIdRouteImport } from './routes/used.$id'
import { Route as AccessoriesCategoryIdRouteImport } from './routes/accessories_.$category.$id'
import { Route as MobilesBrandModelRouteImport } from './routes/mobiles.$brand.$model'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRepairRoute = BookRepairRouteImport.update({
  id: '/book-repair',
  path: '/book-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilesRoute = MobilesRouteImport.update({
  id: '/mobiles',
  path: '/mobiles',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeInRoute = TradeInRouteImport.update({
  id: '/trade-in',
  path: '/trade-in',
  getParentRoute: () => rootRouteImport,
} as any)
const UsedRoute = UsedRouteImport.update({
  id: '/used',
  path: '/used',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesCategoryRoute = AccessoriesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => AccessoriesRoute,
} as any)
const MobilesIndexRoute = MobilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MobilesRoute,
} as any)
const MobilesBrandRoute = MobilesBrandRouteImport.update({
  id: '/$brand',
  path: '/$brand',
  getParentRoute: () => MobilesRoute,
} as any)
const RepairServiceRoute = RepairServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => RepairRoute,
} as any)
const UsedIdRoute = UsedIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsedRoute,
} as any)
const AccessoriesCategoryIdRoute = AccessoriesCategoryIdRouteImport.update({
  id: '/accessories_/$category/$id',
  path: '/accessories/$category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilesBrandModelRoute = MobilesBrandModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => MobilesBrandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/book-repair': typeof BookRepairRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/mobiles': typeof MobilesRouteWithChildren
  '/offers': typeof OffersRoute
  '/repair': typeof RepairRouteWithChildren
  '/software': typeof SoftwareRoute
  '/track': typeof TrackRoute
  '/trade-in': typeof TradeInRoute
  '/used': typeof UsedRouteWithChildren
  '/accessories/$category': typeof AccessoriesCategoryRoute
  '/mobiles/$brand': typeof MobilesBrandRouteWithChildren
  '/repair/$service': typeof RepairServiceRoute
  '/used/$id': typeof UsedIdRoute
  '/mobiles/': typeof MobilesIndexRoute
  '/accessories/$category/$id': typeof AccessoriesCategoryIdRoute
  '/mobiles/$brand/$model': typeof MobilesBrandModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/book-repair': typeof BookRepairRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/offers': typeof OffersRoute
  '/repair': typeof RepairRouteWithChildren
  '/software': typeof SoftwareRoute
  '/track': typeof TrackRoute
  '/trade-in': typeof TradeInRoute
  '/used': typeof UsedRouteWithChildren
  '/accessories/$category': typeof AccessoriesCategoryRoute
  '/mobiles/$brand': typeof MobilesBrandRouteWithChildren
  '/repair/$service': typeof RepairServiceRoute
  '/used/$id': typeof UsedIdRoute
  '/mobiles': typeof MobilesIndexRoute
  '/accessories/$category/$id': typeof AccessoriesCategoryIdRoute
  '/mobiles/$brand/$model': typeof MobilesBrandModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/book-repair': typeof BookRepairRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/mobiles': typeof MobilesRouteWithChildren
  '/offers': typeof OffersRoute
  '/repair': typeof RepairRouteWithChildren
  '/software': typeof SoftwareRoute
  '/track': typeof TrackRoute
  '/trade-in': typeof TradeInRoute
  '/used': typeof UsedRouteWithChildren
  '/accessories/$category': typeof AccessoriesCategoryRoute
  '/mobiles/$brand': typeof MobilesBrandRouteWithChildren
  '/repair/$service': typeof RepairServiceRoute
  '/used/$id': typeof UsedIdRoute
  '/mobiles/': typeof MobilesIndexRoute
  '/accessories_/$category/$id': typeof AccessoriesCategoryIdRoute
  '/mobiles/$brand/$model': typeof MobilesBrandModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessories'
    | '/book-repair'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/mobiles'
    | '/offers'
    | '/repair'
    | '/software'
    | '/track'
    | '/trade-in'
    | '/used'
    | '/accessories/$category'
    | '/mobiles/$brand'
    | '/repair/$service'
    | '/used/$id'
    | '/mobiles/'
    | '/accessories/$category/$id'
    | '/mobiles/$brand/$model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessories'
    | '/book-repair'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/offers'
    | '/repair'
    | '/software'
    | '/track'
    | '/trade-in'
    | '/used'
    | '/accessories/$category'
    | '/mobiles/$brand'
    | '/repair/$service'
    | '/used/$id'
    | '/mobiles'
    | '/accessories/$category/$id'
    | '/mobiles/$brand/$model'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessories'
    | '/book-repair'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/mobiles'
    | '/offers'
    | '/repair'
    | '/software'
    | '/track'
    | '/trade-in'
    | '/used'
    | '/accessories/$category'
    | '/mobiles/$brand'
    | '/repair/$service'
    | '/used/$id'
    | '/mobiles/'
    | '/accessories_/$category/$id'
    | '/mobiles/$brand/$model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessoriesRoute: typeof AccessoriesRouteWithChildren
  BookRepairRoute: typeof BookRepairRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MobilesRoute: typeof MobilesRouteWithChildren
  OffersRoute: typeof OffersRoute
  RepairRoute: typeof RepairRouteWithChildren
  SoftwareRoute: typeof SoftwareRoute
  TrackRoute: typeof TrackRoute
  TradeInRoute: typeof TradeInRoute
  UsedRoute: typeof UsedRouteWithChildren
  AccessoriesCategoryIdRoute: typeof AccessoriesCategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-repair': {
      id: '/book-repair'
      path: '/book-repair'
      fullPath: '/book-repair'
      preLoaderRoute: typeof BookRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobiles': {
      id: '/mobiles'
      path: '/mobiles'
      fullPath: '/mobiles'
      preLoaderRoute: typeof MobilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-in': {
      id: '/trade-in'
      path: '/trade-in'
      fullPath: '/trade-in'
      preLoaderRoute: typeof TradeInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/used': {
      id: '/used'
      path: '/used'
      fullPath: '/used'
      preLoaderRoute: typeof UsedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories/$category': {
      id: '/accessories/$category'
      path: '/$category'
      fullPath: '/accessories/$category'
      preLoaderRoute: typeof AccessoriesCategoryRouteImport
      parentRoute: typeof AccessoriesRoute
    }
    '/mobiles/': {
      id: '/mobiles/'
      path: '/'
      fullPath: '/mobiles/'
      preLoaderRoute: typeof MobilesIndexRouteImport
      parentRoute: typeof MobilesRoute
    }
    '/mobiles/$brand': {
      id: '/mobiles/$brand'
      path: '/$brand'
      fullPath: '/mobiles/$brand'
      preLoaderRoute: typeof MobilesBrandRouteImport
      parentRoute: typeof MobilesRoute
    }
    '/repair/$service': {
      id: '/repair/$service'
      path: '/$service'
      fullPath: '/repair/$service'
      preLoaderRoute: typeof RepairServiceRouteImport
      parentRoute: typeof RepairRoute
    }
    '/used/$id': {
      id: '/used/$id'
      path: '/$id'
      fullPath: '/used/$id'
      preLoaderRoute: typeof UsedIdRouteImport
      parentRoute: typeof UsedRoute
    }
    '/accessories_/$category/$id': {
      id: '/accessories_/$category/$id'
      path: '/accessories/$category/$id'
      fullPath: '/accessories/$category/$id'
      preLoaderRoute: typeof AccessoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobiles/$brand/$model': {
      id: '/mobiles/$brand/$model'
      path: '/$model'
      fullPath: '/mobiles/$brand/$model'
      preLoaderRoute: typeof MobilesBrandModelRouteImport
      parentRoute: typeof MobilesBrandRoute
    }
  }
}

interface AccessoriesRouteChildren {
  AccessoriesCategoryRoute: typeof AccessoriesCategoryRoute
}

const AccessoriesRouteChildren: AccessoriesRouteChildren = {
  AccessoriesCategoryRoute: AccessoriesCategoryRoute,
}

const AccessoriesRouteWithChildren = AccessoriesRoute._addFileChildren(
  AccessoriesRouteChildren,
)

interface MobilesBrandRouteChildren {
  MobilesBrandModelRoute: typeof MobilesBrandModelRoute
}

const MobilesBrandRouteChildren: MobilesBrandRouteChildren = {
  MobilesBrandModelRoute: MobilesBrandModelRoute,
}

const MobilesBrandRouteWithChildren = MobilesBrandRoute._addFileChildren(
  MobilesBrandRouteChildren,
)

interface MobilesRouteChildren {
  MobilesBrandRoute: typeof MobilesBrandRouteWithChildren
  MobilesIndexRoute: typeof MobilesIndexRoute
}

const MobilesRouteChildren: MobilesRouteChildren = {
  MobilesBrandRoute: MobilesBrandRouteWithChildren,
  MobilesIndexRoute: MobilesIndexRoute,
}

const MobilesRouteWithChildren =
  MobilesRoute._addFileChildren(MobilesRouteChildren)

interface RepairRouteChildren {
  RepairServiceRoute: typeof RepairServiceRoute
}

const RepairRouteChildren: RepairRouteChildren = {
  RepairServiceRoute: RepairServiceRoute,
}

const RepairRouteWithChildren =
  RepairRoute._addFileChildren(RepairRouteChildren)

interface UsedRouteChildren {
  UsedIdRoute: typeof UsedIdRoute
}

const UsedRouteChildren: UsedRouteChildren = {
  UsedIdRoute: UsedIdRoute,
}

const UsedRouteWithChildren = UsedRoute._addFileChildren(UsedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessoriesRoute: AccessoriesRouteWithChildren,
  BookRepairRoute: BookRepairRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MobilesRoute: MobilesRouteWithChildren,
  OffersRoute: OffersRoute,
  RepairRoute: RepairRouteWithChildren,
  SoftwareRoute: SoftwareRoute,
  TrackRoute: TrackRoute,
  TradeInRoute: TradeInRoute,
  UsedRoute: UsedRouteWithChildren,
  AccessoriesCategoryIdRoute: AccessoriesCategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
