/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R360ViewerRouteImport } from './routes/360-viewer'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AiRepairRouteImport } from './routes/ai-repair'
import { Route as BatteryCalculatorRouteImport } from './routes/battery-calculator'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookRepairRouteImport } from './routes/book-repair'
import { Route as BundleBuilderRouteImport } from './routes/bundle-builder'
import { Route as CameraCompareRouteImport } from './routes/camera-compare'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MobilesRouteImport } from './routes/mobiles'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PhoneFinderRouteImport } from './routes/phone-finder'
import { Route as PriceTrackerRouteImport } from './routes/price-tracker'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as RepairCalculatorRouteImport } from './routes/repair-calculator'
import { Route as SizeCompareRouteImport } from './routes/size-compare'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as SpinWheelRouteImport } from './routes/spin-wheel'
import { Route as StorageCalculatorRouteImport } from './routes/storage-calculator'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TradeInRouteImport } from './routes/trade-in'
import { Route as UnboxingRouteImport } from './routes/unboxing'
import { Route as UsedRouteImport } from './routes/used'
import { Route as AccessoriesCategoryRouteImport } from './routes/accessories.$category'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as MobilesIndexRouteImport } from './routes/mobiles.index'
import { Route as MobilesBrandRouteImport } from './routes/mobiles.$brand'
import { Route as RepairServiceRouteImport } from './routes/repair.$service'
import { Route as UsedIdRouteImport } from './routes/used.$id'
import { Route as AccessoriesCategoryIdRouteImport } from './routes/accessories_.$category.$id'
import { Route as MobilesBrandModelRouteImport } from './routes/mobiles.$brand.$model'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R360ViewerRoute = R360ViewerRouteImport.update({
  id: '/360-viewer',
  path: '/360-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRepairRoute = AiRepairRouteImport.update({
  id: '/ai-repair',
  path: '/ai-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteryCalculatorRoute = BatteryCalculatorRouteImport.update({
  id: '/battery-calculator',
  path: '/battery-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRepairRoute = BookRepairRouteImport.update({
  id: '/book-repair',
  path: '/book-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleBuilderRoute = BundleBuilderRouteImport.update({
  id: '/bundle-builder',
  path: '/bundle-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraCompareRoute = CameraCompareRouteImport.update({
  id: '/camera-compare',
  path: '/camera-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilesRoute = MobilesRouteImport.update({
  id: '/mobiles',
  path: '/mobiles',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneFinderRoute = PhoneFinderRouteImport.update({
  id: '/phone-finder',
  path: '/phone-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceTrackerRoute = PriceTrackerRouteImport.update({
  id: '/price-tracker',
  path: '/price-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairCalculatorRoute = RepairCalculatorRouteImport.update({
  id: '/repair-calculator',
  path: '/repair-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeCompareRoute = SizeCompareRouteImport.update({
  id: '/size-compare',
  path: '/size-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinWheelRoute = SpinWheelRouteImport.update({
  id: '/spin-wheel',
  path: '/spin-wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageCalculatorRoute = StorageCalculatorRouteImport.update({
  id: '/storage-calculator',
  path: '/storage-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeInRoute = TradeInRouteImport.update({
  id: '/trade-in',
  path: '/trade-in',
  getParentRoute: () => rootRouteImport,
} as any)
const UnboxingRoute = UnboxingRouteImport.update({
  id: '/unboxing',
  path: '/unboxing',
  getParentRoute: () => rootRouteImport,
} as any)
const UsedRoute = UsedRouteImport.update({
  id: '/used',
  path: '/used',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesCategoryRoute = AccessoriesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => AccessoriesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const MobilesIndexRoute = MobilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MobilesRoute,
} as any)
const MobilesBrandRoute = MobilesBrandRouteImport.update({
  id: '/$brand',
  path: '/$brand',
  getParentRoute: () => MobilesRoute,
} as any)
const RepairServiceRoute = RepairServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => RepairRoute,
} as any)
const UsedIdRoute = UsedIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsedRoute,
} as any)
const AccessoriesCategoryIdRoute = AccessoriesCategoryIdRouteImport.update({
  id: '/accessories_/$category/$id',
  path: '/accessories/$category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilesBrandModelRoute = MobilesBrandModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => MobilesBrandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/360-viewer': typeof R360ViewerRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/ai-repair': typeof AiRepairRoute
  '/battery-calculator': typeof BatteryCalculatorRoute
  '/benchmarks': typeof BenchmarksRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-repair': typeof BookRepairRoute
  '/bundle-builder': typeof BundleBuilderRoute
  '/camera-compare': typeof CameraCompareRoute
  '/compare': typeof CompareRoute
  '/compatibility': typeof CompatibilityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/mobiles': typeof MobilesRouteWithChildren
  '/offers': typeof OffersRoute
  '/phone-finder': typeof PhoneFinderRoute
  '/price-tracker': typeof PriceTrackerRoute
  '/repair': typeof RepairRouteWithChildren
  '/repair-calculator': typeof RepairCalculatorRoute
  '/size-compare': typeof SizeCompareRoute
  '/software': typeof SoftwareRoute
  '/spin-wheel': typeof SpinWheelRoute
  '/storage-calculator': typeof StorageCalculatorRoute
  '/track': typeof TrackRoute
  '/trade-in': typeof TradeInRoute
  '/unboxing': typeof UnboxingRoute
  '/used': typeof UsedRouteWithChildren
  '/accessories/$category': typeof AccessoriesCategoryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/mobiles/$brand': typeof MobilesBrandRouteWithChildren
  '/repair/$service': typeof RepairServiceRoute
  '/used/$id': typeof UsedIdRoute
  '/blog/': typeof BlogIndexRoute
  '/mobiles/': typeof MobilesIndexRoute
  '/accessories/$category/$id': typeof AccessoriesCategoryIdRoute
  '/mobiles/$brand/$model': typeof MobilesBrandModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/360-viewer': typeof R360ViewerRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/ai-repair': typeof AiRepairRoute
  '/battery-calculator': typeof BatteryCalculatorRoute
  '/benchmarks': typeof BenchmarksRoute
  '/book-repair': typeof BookRepairRoute
  '/bundle-builder': typeof BundleBuilderRoute
  '/camera-compare': typeof CameraCompareRoute
  '/compare': typeof CompareRoute
  '/compatibility': typeof CompatibilityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/offers': typeof OffersRoute
  '/phone-finder': typeof PhoneFinderRoute
  '/price-tracker': typeof PriceTrackerRoute
  '/repair': typeof RepairRouteWithChildren
  '/repair-calculator': typeof RepairCalculatorRoute
  '/size-compare': typeof SizeCompareRoute
  '/software': typeof SoftwareRoute
  '/spin-wheel': typeof SpinWheelRoute
  '/storage-calculator': typeof StorageCalculatorRoute
  '/track': typeof TrackRoute
  '/trade-in': typeof TradeInRoute
  '/unboxing': typeof UnboxingRoute
  '/used': typeof UsedRouteWithChildren
  '/accessories/$category': typeof AccessoriesCategoryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/mobiles/$brand': typeof MobilesBrandRouteWithChildren
  '/repair/$service': typeof RepairServiceRoute
  '/used/$id': typeof UsedIdRoute
  '/blog': typeof BlogIndexRoute
  '/mobiles': typeof MobilesIndexRoute
  '/accessories/$category/$id': typeof AccessoriesCategoryIdRoute
  '/mobiles/$brand/$model': typeof MobilesBrandModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/360-viewer': typeof R360ViewerRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRouteWithChildren
  '/ai-repair': typeof AiRepairRoute
  '/battery-calculator': typeof BatteryCalculatorRoute
  '/benchmarks': typeof BenchmarksRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-repair': typeof BookRepairRoute
  '/bundle-builder': typeof BundleBuilderRoute
  '/camera-compare': typeof CameraCompareRoute
  '/compare': typeof CompareRoute
  '/compatibility': typeof CompatibilityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/mobiles': typeof MobilesRouteWithChildren
  '/offers': typeof OffersRoute
  '/phone-finder': typeof PhoneFinderRoute
  '/price-tracker': typeof PriceTrackerRoute
  '/repair': typeof RepairRouteWithChildren
  '/repair-calculator': typeof RepairCalculatorRoute
  '/size-compare': typeof SizeCompareRoute
  '/software': typeof SoftwareRoute
  '/spin-wheel': typeof SpinWheelRoute
  '/storage-calculator': typeof StorageCalculatorRoute
  '/track': typeof TrackRoute
  '/trade-in': typeof TradeInRoute
  '/unboxing': typeof UnboxingRoute
  '/used': typeof UsedRouteWithChildren
  '/accessories/$category': typeof AccessoriesCategoryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/mobiles/$brand': typeof MobilesBrandRouteWithChildren
  '/repair/$service': typeof RepairServiceRoute
  '/used/$id': typeof UsedIdRoute
  '/blog/': typeof BlogIndexRoute
  '/mobiles/': typeof MobilesIndexRoute
  '/accessories_/$category/$id': typeof AccessoriesCategoryIdRoute
  '/mobiles/$brand/$model': typeof MobilesBrandModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/360-viewer'
    | '/about'
    | '/accessories'
    | '/ai-repair'
    | '/battery-calculator'
    | '/benchmarks'
    | '/blog'
    | '/book-repair'
    | '/bundle-builder'
    | '/camera-compare'
    | '/compare'
    | '/compatibility'
    | '/contact'
    | '/faq'
    | '/mobiles'
    | '/offers'
    | '/phone-finder'
    | '/price-tracker'
    | '/repair'
    | '/repair-calculator'
    | '/size-compare'
    | '/software'
    | '/spin-wheel'
    | '/storage-calculator'
    | '/track'
    | '/trade-in'
    | '/unboxing'
    | '/used'
    | '/accessories/$category'
    | '/blog/$slug'
    | '/mobiles/$brand'
    | '/repair/$service'
    | '/used/$id'
    | '/blog/'
    | '/mobiles/'
    | '/accessories/$category/$id'
    | '/mobiles/$brand/$model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/360-viewer'
    | '/about'
    | '/accessories'
    | '/ai-repair'
    | '/battery-calculator'
    | '/benchmarks'
    | '/book-repair'
    | '/bundle-builder'
    | '/camera-compare'
    | '/compare'
    | '/compatibility'
    | '/contact'
    | '/faq'
    | '/offers'
    | '/phone-finder'
    | '/price-tracker'
    | '/repair'
    | '/repair-calculator'
    | '/size-compare'
    | '/software'
    | '/spin-wheel'
    | '/storage-calculator'
    | '/track'
    | '/trade-in'
    | '/unboxing'
    | '/used'
    | '/accessories/$category'
    | '/blog/$slug'
    | '/mobiles/$brand'
    | '/repair/$service'
    | '/used/$id'
    | '/blog'
    | '/mobiles'
    | '/accessories/$category/$id'
    | '/mobiles/$brand/$model'
  id:
    | '__root__'
    | '/'
    | '/360-viewer'
    | '/about'
    | '/accessories'
    | '/ai-repair'
    | '/battery-calculator'
    | '/benchmarks'
    | '/blog'
    | '/book-repair'
    | '/bundle-builder'
    | '/camera-compare'
    | '/compare'
    | '/compatibility'
    | '/contact'
    | '/faq'
    | '/mobiles'
    | '/offers'
    | '/phone-finder'
    | '/price-tracker'
    | '/repair'
    | '/repair-calculator'
    | '/size-compare'
    | '/software'
    | '/spin-wheel'
    | '/storage-calculator'
    | '/track'
    | '/trade-in'
    | '/unboxing'
    | '/used'
    | '/accessories/$category'
    | '/blog/$slug'
    | '/mobiles/$brand'
    | '/repair/$service'
    | '/used/$id'
    | '/blog/'
    | '/mobiles/'
    | '/accessories_/$category/$id'
    | '/mobiles/$brand/$model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R360ViewerRoute: typeof R360ViewerRoute
  AboutRoute: typeof AboutRoute
  AccessoriesRoute: typeof AccessoriesRouteWithChildren
  AiRepairRoute: typeof AiRepairRoute
  BatteryCalculatorRoute: typeof BatteryCalculatorRoute
  BenchmarksRoute: typeof BenchmarksRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookRepairRoute: typeof BookRepairRoute
  BundleBuilderRoute: typeof BundleBuilderRoute
  CameraCompareRoute: typeof CameraCompareRoute
  CompareRoute: typeof CompareRoute
  CompatibilityRoute: typeof CompatibilityRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MobilesRoute: typeof MobilesRouteWithChildren
  OffersRoute: typeof OffersRoute
  PhoneFinderRoute: typeof PhoneFinderRoute
  PriceTrackerRoute: typeof PriceTrackerRoute
  RepairRoute: typeof RepairRouteWithChildren
  RepairCalculatorRoute: typeof RepairCalculatorRoute
  SizeCompareRoute: typeof SizeCompareRoute
  SoftwareRoute: typeof SoftwareRoute
  SpinWheelRoute: typeof SpinWheelRoute
  StorageCalculatorRoute: typeof StorageCalculatorRoute
  TrackRoute: typeof TrackRoute
  TradeInRoute: typeof TradeInRoute
  UnboxingRoute: typeof UnboxingRoute
  UsedRoute: typeof UsedRouteWithChildren
  AccessoriesCategoryIdRoute: typeof AccessoriesCategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/360-viewer': {
      id: '/360-viewer'
      path: '/360-viewer'
      fullPath: '/360-viewer'
      preLoaderRoute: typeof R360ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-repair': {
      id: '/ai-repair'
      path: '/ai-repair'
      fullPath: '/ai-repair'
      preLoaderRoute: typeof AiRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battery-calculator': {
      id: '/battery-calculator'
      path: '/battery-calculator'
      fullPath: '/battery-calculator'
      preLoaderRoute: typeof BatteryCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-repair': {
      id: '/book-repair'
      path: '/book-repair'
      fullPath: '/book-repair'
      preLoaderRoute: typeof BookRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle-builder': {
      id: '/bundle-builder'
      path: '/bundle-builder'
      fullPath: '/bundle-builder'
      preLoaderRoute: typeof BundleBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera-compare': {
      id: '/camera-compare'
      path: '/camera-compare'
      fullPath: '/camera-compare'
      preLoaderRoute: typeof CameraCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobiles': {
      id: '/mobiles'
      path: '/mobiles'
      fullPath: '/mobiles'
      preLoaderRoute: typeof MobilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-finder': {
      id: '/phone-finder'
      path: '/phone-finder'
      fullPath: '/phone-finder'
      preLoaderRoute: typeof PhoneFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-tracker': {
      id: '/price-tracker'
      path: '/price-tracker'
      fullPath: '/price-tracker'
      preLoaderRoute: typeof PriceTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-calculator': {
      id: '/repair-calculator'
      path: '/repair-calculator'
      fullPath: '/repair-calculator'
      preLoaderRoute: typeof RepairCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-compare': {
      id: '/size-compare'
      path: '/size-compare'
      fullPath: '/size-compare'
      preLoaderRoute: typeof SizeCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spin-wheel': {
      id: '/spin-wheel'
      path: '/spin-wheel'
      fullPath: '/spin-wheel'
      preLoaderRoute: typeof SpinWheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage-calculator': {
      id: '/storage-calculator'
      path: '/storage-calculator'
      fullPath: '/storage-calculator'
      preLoaderRoute: typeof StorageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-in': {
      id: '/trade-in'
      path: '/trade-in'
      fullPath: '/trade-in'
      preLoaderRoute: typeof TradeInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unboxing': {
      id: '/unboxing'
      path: '/unboxing'
      fullPath: '/unboxing'
      preLoaderRoute: typeof UnboxingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/used': {
      id: '/used'
      path: '/used'
      fullPath: '/used'
      preLoaderRoute: typeof UsedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories/$category': {
      id: '/accessories/$category'
      path: '/$category'
      fullPath: '/accessories/$category'
      preLoaderRoute: typeof AccessoriesCategoryRouteImport
      parentRoute: typeof AccessoriesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/mobiles/': {
      id: '/mobiles/'
      path: '/'
      fullPath: '/mobiles/'
      preLoaderRoute: typeof MobilesIndexRouteImport
      parentRoute: typeof MobilesRoute
    }
    '/mobiles/$brand': {
      id: '/mobiles/$brand'
      path: '/$brand'
      fullPath: '/mobiles/$brand'
      preLoaderRoute: typeof MobilesBrandRouteImport
      parentRoute: typeof MobilesRoute
    }
    '/repair/$service': {
      id: '/repair/$service'
      path: '/$service'
      fullPath: '/repair/$service'
      preLoaderRoute: typeof RepairServiceRouteImport
      parentRoute: typeof RepairRoute
    }
    '/used/$id': {
      id: '/used/$id'
      path: '/$id'
      fullPath: '/used/$id'
      preLoaderRoute: typeof UsedIdRouteImport
      parentRoute: typeof UsedRoute
    }
    '/accessories_/$category/$id': {
      id: '/accessories_/$category/$id'
      path: '/accessories/$category/$id'
      fullPath: '/accessories/$category/$id'
      preLoaderRoute: typeof AccessoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobiles/$brand/$model': {
      id: '/mobiles/$brand/$model'
      path: '/$model'
      fullPath: '/mobiles/$brand/$model'
      preLoaderRoute: typeof MobilesBrandModelRouteImport
      parentRoute: typeof MobilesBrandRoute
    }
  }
}

interface AccessoriesRouteChildren {
  AccessoriesCategoryRoute: typeof AccessoriesCategoryRoute
}

const AccessoriesRouteChildren: AccessoriesRouteChildren = {
  AccessoriesCategoryRoute: AccessoriesCategoryRoute,
}

const AccessoriesRouteWithChildren = AccessoriesRoute._addFileChildren(
  AccessoriesRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface MobilesBrandRouteChildren {
  MobilesBrandModelRoute: typeof MobilesBrandModelRoute
}

const MobilesBrandRouteChildren: MobilesBrandRouteChildren = {
  MobilesBrandModelRoute: MobilesBrandModelRoute,
}

const MobilesBrandRouteWithChildren = MobilesBrandRoute._addFileChildren(
  MobilesBrandRouteChildren,
)

interface MobilesRouteChildren {
  MobilesBrandRoute: typeof MobilesBrandRouteWithChildren
  MobilesIndexRoute: typeof MobilesIndexRoute
}

const MobilesRouteChildren: MobilesRouteChildren = {
  MobilesBrandRoute: MobilesBrandRouteWithChildren,
  MobilesIndexRoute: MobilesIndexRoute,
}

const MobilesRouteWithChildren =
  MobilesRoute._addFileChildren(MobilesRouteChildren)

interface RepairRouteChildren {
  RepairServiceRoute: typeof RepairServiceRoute
}

const RepairRouteChildren: RepairRouteChildren = {
  RepairServiceRoute: RepairServiceRoute,
}

const RepairRouteWithChildren =
  RepairRoute._addFileChildren(RepairRouteChildren)

interface UsedRouteChildren {
  UsedIdRoute: typeof UsedIdRoute
}

const UsedRouteChildren: UsedRouteChildren = {
  UsedIdRoute: UsedIdRoute,
}

const UsedRouteWithChildren = UsedRoute._addFileChildren(UsedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R360ViewerRoute: R360ViewerRoute,
  AboutRoute: AboutRoute,
  AccessoriesRoute: AccessoriesRouteWithChildren,
  AiRepairRoute: AiRepairRoute,
  BatteryCalculatorRoute: BatteryCalculatorRoute,
  BenchmarksRoute: BenchmarksRoute,
  BlogRoute: BlogRouteWithChildren,
  BookRepairRoute: BookRepairRoute,
  BundleBuilderRoute: BundleBuilderRoute,
  CameraCompareRoute: CameraCompareRoute,
  CompareRoute: CompareRoute,
  CompatibilityRoute: CompatibilityRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MobilesRoute: MobilesRouteWithChildren,
  OffersRoute: OffersRoute,
  PhoneFinderRoute: PhoneFinderRoute,
  PriceTrackerRoute: PriceTrackerRoute,
  RepairRoute: RepairRouteWithChildren,
  RepairCalculatorRoute: RepairCalculatorRoute,
  SizeCompareRoute: SizeCompareRoute,
  SoftwareRoute: SoftwareRoute,
  SpinWheelRoute: SpinWheelRoute,
  StorageCalculatorRoute: StorageCalculatorRoute,
  TrackRoute: TrackRoute,
  TradeInRoute: TradeInRoute,
  UnboxingRoute: UnboxingRoute,
  UsedRoute: UsedRouteWithChildren,
  AccessoriesCategoryIdRoute: AccessoriesCategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
